[project]
name = "polish-names"
version = "0.1.0"
description = "Polish Baby Names"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.2.0",
    "jupyter>=1.1.1",
    "jupyterlab>=4.5.4",
    "notebook>=7.5.3",
    "plotly>=6.5.2",
    "polars>=1.38.1",
]
